### ISSUE TITLE
How does fermium differ from sdl2/sdl2-sys?

### ISSUE THREAD

**Issue by 17cupsofcoffee** [Lokathor/fermium#18]
`fermium` looks cool, but I couldn't really decipher from the README what the end goal of the project is - is this meant to be the groundwork for a different (better?) set of Rust-y bindings, or is it intended to be a pure one-to-one mapping of the C API? And if the latter, are there any differences between how you're approaching it and how `sdl2-sys` approaches it?

**Comment by Lokathor** [comment]
`fermium` focuses on the bindings layer of things. It acts as a replacement for `sdl2-sys`.

There are some differences, but the biggest one to me is that I know all of what's going on and can change things here myself if I need changes, instead of asking someone else to do work on my behalf and then waiting.

Technically, the biggest difference is that `fermium` uses the more correct "scoped constant" option for consts.

**Comment by 17cupsofcoffee** [comment]
Makes total sense, thanks for the answer 😄
